; Packed charset image — generated by tools/gencharset.js (runtime $D800)
; 0–15 walls; 16–63 doomfont+gaps; 64–89 A–Z; 90–105 floors
; Gaps: skull@16 arrows@17–20 solid/ITEM@21 logo@22–28,35–36
!zone charset

charset_image
	!byte $ff,$ef,$fe,$ff,$ff,$bf,$fb,$ff	; wall 0
	!byte $ef,$ee,$fe,$ff,$bf,$bb,$fb,$ff	; wall 1
	!byte $ef,$ee,$ee,$fe,$bf,$bb,$bb,$fb	; wall 2
	!byte $ef,$ee,$ee,$ae,$ba,$bb,$bb,$fb	; wall 3
	!byte $eb,$ee,$ee,$ae,$aa,$ba,$bb,$bb	; wall 4
	!byte $aa,$ea,$ee,$ae,$aa,$ba,$bb,$ab	; wall 5
	!byte $aa,$ea,$ae,$aa,$aa,$ba,$ab,$aa	; wall 6
	!byte $a2,$ea,$ae,$aa,$28,$ba,$ab,$8a	; wall 7
	!byte $aa,$aa,$a2,$aa,$2a,$a8,$8a,$aa	; wall 8
	!byte $a8,$88,$8a,$aa,$a2,$22,$2a,$aa	; wall 9
	!byte $a8,$88,$88,$8a,$a2,$22,$22,$2a	; wall 10
	!byte $28,$88,$88,$88,$82,$22,$22,$22	; wall 11
	!byte $08,$88,$88,$80,$02,$22,$22,$20	; wall 12
	!byte $00,$08,$88,$80,$00,$02,$22,$20	; wall 13
	!byte $00,$08,$80,$00,$00,$02,$20,$00	; wall 14
	!byte $00,$00,$00,$00,$00,$00,$00,$00	; wall 15
	!byte $3e,$7f,$7f,$49,$49,$3e,$2a,$00	; skull MENU_CURSOR
	!byte $ff,$ff,$9d,$60,$60,$9d,$ff,$ff	; map arrow 0
	!byte $e7,$db,$db,$e7,$e7,$e7,$c3,$e7	; map arrow 1
	!byte $ff,$ff,$b9,$06,$06,$b9,$ff,$ff	; map arrow 2
	!byte $e7,$c3,$e7,$e7,$e7,$db,$db,$e7	; map arrow 3
	!byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff	; solid MAP_SOLID/ITEM_PAT
	!byte $c0,$e0,$70,$38,$1c,$0e,$07,$03
	!byte $03,$07,$0e,$1c,$38,$70,$e0,$c0
	!byte $c3,$e7,$7e,$3c,$3c,$7e,$e7,$c3
	!byte $ff,$7f,$3f,$1f,$0f,$07,$03,$01
	!byte $ff,$fe,$fc,$f8,$f0,$e0,$c0,$80
	!byte $03,$03,$03,$03,$03,$03,$03,$03
	!byte $00,$80,$c0,$e0,$f0,$f8,$fc,$fe
	!byte $ff,$b1,$f9,$31,$a9,$a9,$10,$ff
	!byte $e7,$ff,$66,$18,$5a,$3c,$5a,$3c
	!byte $00,$00,$40,$3f,$e6,$c0,$00,$00
	!byte $00,$00,$00,$00,$00,$00,$00,$00	; space
	!byte $18,$18,$18,$18,$00,$18,$18,$00
	!byte $00,$6a,$ff,$fe,$7e,$ea,$c0,$00
	!byte $33,$33,$cc,$cc,$33,$33,$cc,$cc
	!byte $00,$01,$03,$07,$0f,$1f,$3f,$7f
	!byte $63,$67,$0e,$1c,$38,$73,$63,$00
	!byte $00,$00,$7e,$3e,$68,$60,$00,$00
	!byte $18,$18,$10,$00,$00,$00,$00,$00
	!byte $3f,$07,$b3,$a1,$e5,$7f,$3f,$1f
	!byte $fc,$fc,$e5,$8d,$9f,$fe,$fc,$f8
	!byte $3c,$3a,$3f,$18,$0f,$0e,$07,$00
	!byte $3c,$5c,$fc,$18,$f0,$70,$e0,$00
	!byte $00,$00,$00,$00,$00,$18,$18,$10
	!byte $00,$00,$00,$3c,$3c,$00,$00,$00
	!byte $00,$00,$00,$00,$00,$18,$18,$00
	!byte $7f,$3e,$41,$5d,$77,$63,$77,$00
	!byte $3e,$7f,$63,$63,$63,$7f,$3e,$00
	!byte $38,$3c,$0c,$0c,$0c,$1e,$1e,$00
	!byte $7e,$7f,$07,$0e,$38,$7f,$7f,$00
	!byte $7e,$7f,$03,$1e,$03,$7f,$7e,$00
	!byte $63,$63,$7f,$3f,$03,$03,$03,$00
	!byte $7f,$7f,$60,$3e,$03,$7f,$7e,$00
	!byte $3e,$7e,$60,$7e,$63,$7f,$3e,$00
	!byte $7e,$7f,$03,$03,$03,$03,$03,$00
	!byte $3e,$7f,$63,$3e,$63,$7f,$3e,$00
	!byte $3e,$7f,$63,$3f,$03,$3f,$3e,$00
	!byte $00,$18,$18,$00,$18,$18,$00,$00
	!byte $1c,$3c,$6c,$53,$41,$65,$55,$7f
	!byte $00,$00,$02,$ff,$df,$62,$40,$00
	!byte $00,$40,$a0,$fe,$e1,$e1,$fe,$00
	!byte $1c,$fe,$fe,$ff,$37,$39,$1e,$00
	!byte $7e,$7f,$03,$1f,$00,$18,$18,$00
	!byte $06,$1f,$33,$33,$6f,$63,$63,$00	; 'A'
	!byte $7e,$7f,$03,$7e,$63,$7f,$7e,$00	; 'B'
	!byte $3f,$7f,$60,$60,$60,$7f,$3f,$00	; 'C'
	!byte $7e,$7f,$03,$63,$63,$7f,$7e,$00	; 'D'
	!byte $1f,$3f,$70,$7e,$70,$3f,$1f,$00	; 'E'
	!byte $3f,$7f,$60,$7e,$60,$60,$60,$00	; 'F'
	!byte $3f,$7f,$60,$63,$63,$7f,$3f,$00	; 'G'
	!byte $63,$63,$63,$7f,$7f,$63,$63,$00	; 'H'
	!byte $0c,$0c,$0c,$0c,$0c,$0c,$0c,$00	; 'I'
	!byte $06,$06,$06,$06,$06,$3e,$3c,$00	; 'J'
	!byte $66,$6c,$78,$78,$6c,$66,$63,$00	; 'K'
	!byte $60,$60,$60,$60,$60,$7e,$3e,$00	; 'L'
	!byte $62,$77,$7f,$7f,$6b,$63,$63,$00	; 'M'
	!byte $23,$73,$7b,$7f,$6f,$67,$62,$00	; 'N'
	!byte $3e,$7f,$63,$63,$63,$7f,$3e,$00	; 'O'
	!byte $7e,$7f,$03,$7f,$7e,$60,$60,$00	; 'P'
	!byte $3e,$7f,$63,$63,$63,$7f,$3e,$06	; 'Q'
	!byte $7e,$7f,$03,$7f,$7e,$63,$63,$00	; 'R'
	!byte $3f,$7f,$60,$3e,$03,$7f,$7e,$00	; 'S'
	!byte $3f,$3f,$0c,$0c,$0c,$0c,$0c,$00	; 'T'
	!byte $63,$63,$63,$63,$63,$7f,$3e,$00	; 'U'
	!byte $63,$63,$63,$36,$36,$1c,$1c,$00	; 'V'
	!byte $63,$63,$6b,$7f,$7f,$77,$23,$00	; 'W'
	!byte $63,$77,$3e,$1c,$3e,$77,$63,$00	; 'X'
	!byte $66,$66,$7e,$3c,$18,$18,$18,$00	; 'Y'
	!byte $7f,$7f,$0e,$1c,$38,$7f,$7f,$00	; 'Z'
	!byte $ff,$df,$ff,$fd,$ff,$bf,$ff,$fb	; floor 0
	!byte $ff,$cf,$ff,$fc,$ff,$9f,$ff,$f9	; floor 1
	!byte $ff,$8f,$ff,$f8,$ff,$1f,$ff,$f1	; floor 2
	!byte $ff,$87,$ff,$f0,$ff,$0f,$ff,$e1	; floor 3
	!byte $ff,$07,$ff,$e0,$ff,$0e,$ff,$c1	; floor 4
	!byte $ff,$06,$ff,$60,$ff,$0c,$ff,$c0	; floor 5
	!byte $ff,$02,$ff,$20,$ff,$04,$ff,$40	; floor 6
	!byte $ef,$02,$7f,$20,$fe,$04,$ef,$40	; floor 7
	!byte $ef,$00,$bf,$00,$fb,$00,$df,$00	; floor 8
	!byte $9f,$00,$f9,$00,$cf,$00,$fc,$00	; floor 9
	!byte $1f,$00,$f1,$00,$8f,$00,$f8,$00	; floor 10
	!byte $1e,$00,$e1,$00,$0f,$00,$f0,$00	; floor 11
	!byte $0e,$00,$e0,$00,$07,$00,$70,$00	; floor 12
	!byte $0c,$00,$c0,$00,$06,$00,$60,$00	; floor 13
	!byte $04,$00,$40,$00,$02,$00,$20,$00	; floor 14
	!byte $00,$00,$00,$00,$00,$00,$00,$00	; floor 15
