; Logo layout constants — payload is screens/logo.bin → FRAMEBUFFER
; Generated by tools/genlogo.js
LOGO_W = 26
LOGO_H = 13
LOGO_COL = 7		; centered in 40 columns
LOGO_ROW = 1
LOGO_PAIR_COUNT = 20
LOGO_RLE_COUNT = 223
LOGO_PAIR_CHARS = FRAMEBUFFER
LOGO_PAIR_COLS = FRAMEBUFFER + LOGO_PAIR_COUNT
LOGO_RLE = FRAMEBUFFER + LOGO_PAIR_COUNT * 2

