; Logo layout constants — payload is screens/logo.bin → SCREENBUFFER
; Generated by tools/genlogo.js
LOGO_W = 26
LOGO_H = 13
LOGO_COL = 7		; centered in 40 columns
LOGO_ROW = 1
LOGO_PAIR_COUNT = 20
LOGO_RLE_COUNT = 223
LOGO_PAIR_CHARS = SCREENBUFFER
LOGO_PAIR_COLS = SCREENBUFFER + LOGO_PAIR_COUNT
LOGO_RLE = SCREENBUFFER + LOGO_PAIR_COUNT * 2

