#!/usr/bin/env python3
"""Emit menu_imports.asm from squaredoom.lbl for screens/menu.asm."""

from __future__ import annotations

import re
import sys
from pathlib import Path

# Labels the menu overlay jsr/reads (resident mid / low)
IMPORT_LABELS = [
    "MENU_BASE",
    "MENU_LIMIT",
    "SCREENBUFFER",
    "PATTERNBUFFER",
    "UI_LOAD_MAX",
    "clear_screen",
    "clear_row",
    "print_centered",
    "print_at",
    "cell_addr",
    "ascii_to_scr",
    "str_len",
    "wait_raster",
    "wait_frame",
    "wait_frames_30",
    "wait_frames_x",
    "wait_key",
    "LoadPrg",
    "load_do_pad",
    "ui_name_buf",
    "play_sound",
    "ui_read_keys",
    "ui_wait_esc_up",
    "difficulty",
    "episode",
    "level_num",
    "effects_vol",
    "music_vol",
    "menu_can_ret",
    "menu_id",
    "menu_item",
    "menu_size",
    "menu_stack_d",
    "menu_stk_m",
    "menu_stk_i",
    "ui_text_col",
    "pr_row",
    "pr_col",
    "pr_len",
    "input_paused",
    "hud_dirty",
    "ui_buf_id",
    "sound_index",
    "ui_pressed",
    "ui_keys",
]

LBL_RE = re.compile(
    r"^al\s+C:([0-9a-fA-F]+)\s+\.([A-Za-z_][A-Za-z0-9_]*)$"
)


def parse_lbl(path: Path) -> dict[str, int]:
    out: dict[str, int] = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = LBL_RE.match(line.strip())
        if m:
            out[m.group(2)] = int(m.group(1), 16)
    return out


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    lbl_path = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "squaredoom.lbl"
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else root / "menu_imports.asm"

    if not lbl_path.is_file():
        raise SystemExit(f"missing {lbl_path}")

    syms = parse_lbl(lbl_path)
    missing = [n for n in IMPORT_LABELS if n not in syms]
    if missing:
        raise SystemExit(f"missing labels in {lbl_path}: {', '.join(missing)}")

    lines = [
        "; Auto-generated by tools/gen_menu_imports.py — do not edit",
        f"MENU_BASE = ${syms['MENU_BASE']:04x}",
        f"MENU_LIMIT = ${syms['MENU_LIMIT']:04x}",
        f"SCREENBUFFER = ${syms['SCREENBUFFER']:04x}",
        f"PATTERNBUFFER = ${syms['PATTERNBUFFER']:04x}",
        f"UI_LOAD_MAX = {syms['UI_LOAD_MAX']}",
        "MSG_LET0 = 64",
        "MENU_CURSOR = 16",
        "SOUND_PISTOL = 7",
        "SOUND_STNMOV = 13",
        "UI_UP = 1",
        "UI_DOWN = 2",
        "UI_LEFT = 4",
        "UI_RIGHT = 8",
        "UI_SELECT = 16",
        "UI_ESC = 32",
        "",
        "; Zero page (subset used by menu overlay)",
        "tmp0 = $23",
        "tmp1 = $24",
        "tmp2 = $25",
        "tmp3 = $26",
        "tmp4 = $27",
        "tmp5 = $28",
        "ptr_l = $29",
        "ptr_h = $2a",
        "aux_l = $3b",
        "aux_h = $3c",
        "ui_str_l = $9d",
        "ui_str_h = $9e",
        "",
    ]

    skip = {
        "MENU_BASE",
        "MENU_LIMIT",
        "SCREENBUFFER",
        "PATTERNBUFFER",
        "UI_LOAD_MAX",
    }
    for name in IMPORT_LABELS:
        if name in skip:
            continue
        lines.append(f"{name} = ${syms[name]:04x}")

    lines.extend(
        [
            "",
            "LOGO_W = 26",
            "LOGO_H = 13",
            "LOGO_COL = 7",
            "LOGO_ROW = 1",
            "LOGO_PAIR_COUNT = 20",
            "LOGO_PAIR_CHARS = SCREENBUFFER",
            "LOGO_PAIR_COLS = SCREENBUFFER + LOGO_PAIR_COUNT",
            "LOGO_RLE = SCREENBUFFER + LOGO_PAIR_COUNT * 2",
            "",
        ]
    )

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"wrote {out_path} (MENU_BASE=${syms['MENU_BASE']:04x} "
        f"limit=${syms['MENU_LIMIT']:04x} screen=${syms['SCREENBUFFER']:04x})"
    )


if __name__ == "__main__":
    main()
