#!/usr/bin/env python3
"""Pack textures/wipsprite.png as one hires VIC sprite (24×21, near-white on)."""
from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "textures" / "wipsprite.png"
OUT = ROOT / "tmp" / "menu_wip_spr.asm"

SPR_W = 24
SPR_H = 21
LUMA_ON = 128


def pack_sprite(grid: list[list[int]]) -> list[int]:
	raw = []
	gh = len(grid)
	gw = len(grid[0]) if gh else 0
	for row in range(SPR_H):
		for col in range(3):
			b = 0
			for bit in range(8):
				x = col * 8 + bit
				y = row
				if 0 <= y < gh and 0 <= x < gw and grid[y][x]:
					b |= 0x80 >> bit
			raw.append(b)
	raw.append(0)
	return raw


def fmt_bytes(data: list[int], per_line: int = 16) -> list[str]:
	lines = []
	for i in range(0, len(data), per_line):
		chunk = data[i : i + per_line]
		lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
	return lines


def main() -> None:
	im = Image.open(SRC).convert("RGBA")
	w, h = im.size
	if w != SPR_W or h != SPR_H:
		raise SystemExit(f"{SRC.name} is {w}x{h}, need {SPR_W}x{SPR_H}")
	px = im.load()
	grid = [[0] * SPR_W for _ in range(SPR_H)]
	for y in range(h):
		for x in range(w):
			r, g, b, a = px[x, y]
			if a < 16:
				continue
			if (r + g + b) >= LUMA_ON * 3:
				grid[y][x] = 1
	blob = pack_sprite(grid)
	lines = [
		"; Auto-generated by tools/gen_menu_wip_sprite.py",
		"WIP_SPR_COUNT\t= 1",
		"WIP_SPR_W\t= 24",
		"",
		"menu_wip_spr",
	]
	lines.extend(fmt_bytes(blob))
	lines.append("")
	OUT.parent.mkdir(parents=True, exist_ok=True)
	OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
	print(f"wrote {OUT.relative_to(ROOT)} bytes={len(blob)}")


if __name__ == "__main__":
	main()
