#!/usr/bin/env python3
"""Pack m_skull_c64.png (base layers) + m_skull2_c64.png (red/white overlay diff)."""
from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
BASE_PNG = ROOT / "itemgraphics" / "multicolour" / "m_skull_c64.png"
DIFF_PNG = ROOT / "itemgraphics" / "multicolour" / "m_skull2_c64.png"
OUT = ROOT / "tmp" / "menu_cursor_spr.asm"
PREVIEW = ROOT / "tmp" / "menu_cursor_preview.png"

SPR_W = 24
SPR_H = 21

C64_NAMES = (
	"black", "white", "red", "cyan", "purple", "green", "blue", "yellow",
	"orange", "brown", "ltred", "dkgrey", "grey", "ltgreen", "ltblue", "ltgrey",
)
PEPTO_RGB = (
	(0x00, 0x00, 0x00),
	(0xFF, 0xFF, 0xFF),
	(0x68, 0x37, 0x2B),
	(0x70, 0xA4, 0xB2),
	(0x6F, 0x3D, 0x86),
	(0x58, 0x8D, 0x43),
	(0x35, 0x28, 0x79),
	(0xB8, 0xC7, 0x6F),
	(0x6F, 0x4F, 0x25),
	(0x43, 0x39, 0x00),
	(0x9A, 0x67, 0x59),
	(0x44, 0x44, 0x44),
	(0x6C, 0x6C, 0x6C),
	(0x9A, 0xD2, 0x84),
	(0x6C, 0x5E, 0xB5),
	(0x95, 0x95, 0x95),
)


def nearest_pepto(rgb: tuple[int, int, int]) -> int:
	best = 0
	best_d = 10**9
	for i, (cr, cg, cb) in enumerate(PEPTO_RGB):
		d = (rgb[0] - cr) ** 2 + (rgb[1] - cg) ** 2 + (rgb[2] - cb) ** 2
		if d < best_d:
			best_d = d
			best = i
	return best


def pack_sprite(grid: list[list[int]]) -> list[int]:
	raw = []
	gh = len(grid)
	gw = len(grid[0]) if gh else 0
	for row in range(SPR_H):
		for col in range(3):
			b = 0
			for bit in range(8):
				x = col * 8 + bit
				y = row
				if 0 <= y < gh and 0 <= x < gw and grid[y][x]:
					b |= 0x80 >> bit
			raw.append(b)
	raw.append(0)
	return raw


def fmt_bytes(data: list[int], per_line: int = 16) -> list[str]:
	lines = []
	for i in range(0, len(data), per_line):
		chunk = data[i : i + per_line]
		lines.append("\t!byte " + ",".join(f"${b:02x}" for b in chunk))
	return lines


def layer_grid(w: int, h: int, pred) -> list[list[int]]:
	g = [[0] * SPR_W for _ in range(SPR_H)]
	for y in range(h):
		for x in range(w):
			if pred(x, y):
				g[y][x] = 1
	return g


def main() -> None:
	base = Image.open(BASE_PNG).convert("RGBA")
	diff = Image.open(DIFF_PNG).convert("RGBA")
	if base.size != diff.size:
		raise SystemExit(f"skull size mismatch {base.size} vs {diff.size}")
	w, h = base.size
	bp, dp = base.load(), diff.load()

	base_idx = [[None] * w for _ in range(h)]
	used: set[int] = set()
	for y in range(h):
		for x in range(w):
			r, g, b, a = bp[x, y]
			if a < 16:
				continue
			i = nearest_pepto((r, g, b))
			if i == 0:
				continue
			base_idx[y][x] = i
			used.add(i)
	base_cols = sorted(used, key=lambda i: -(sum(PEPTO_RGB[i])))

	ov_white = [[0] * SPR_W for _ in range(SPR_H)]
	ov_red = [[0] * SPR_W for _ in range(SPR_H)]
	for y in range(h):
		for x in range(w):
			ba, da = bp[x, y], dp[x, y]
			if da[:3] == ba[:3] and da[3] == ba[3]:
				continue
			if da[3] < 16:
				continue
			i = nearest_pepto(da[:3])
			if i == 1:
				ov_white[y][x] = 1
			elif i == 2:
				ov_red[y][x] = 1
			else:
				raise SystemExit(f"overlay pixel not red/white at {x},{y}: {C64_NAMES[i]}")

	# Front to back: white overlay, red overlay, then base brightest-first
	sprites: list[list[int]] = []
	cols: list[int] = [1, 2]
	sprites.append(pack_sprite(ov_white))
	sprites.append(pack_sprite(ov_red))
	for col in base_cols:
		grid = layer_grid(
			w, h, lambda x, y, c=col: base_idx[y][x] == c
		)
		sprites.append(pack_sprite(grid))
		cols.append(col)

	preview = Image.new("RGBA", (SPR_W * 2, SPR_H), (0, 0, 0, 0))
	pp = preview.load()
	# frame 0: base only; frame 1: base + overlay
	layer_rgb = [PEPTO_RGB[c] for c in cols]
	for fi in range(2):
		start = 0 if fi else 2
		for li in range(len(sprites) - 1, start - 1, -1):
			rgb = layer_rgb[li]
			raw = sprites[li]
			for row in range(SPR_H):
				for col in range(3):
					b = raw[row * 3 + col]
					for bit in range(8):
						if b & (0x80 >> bit):
							pp[fi * SPR_W + col * 8 + bit, row] = (*rgb, 255)

	blobs: list[int] = []
	for s in sprites:
		blobs.extend(s)
	col_bytes = ",".join(f"${c:02x}" for c in cols)
	col_names = ", ".join(C64_NAMES[c] for c in cols)
	n = len(sprites)
	lines = [
		"; Auto-generated by tools/gen_menu_cursor_sprites.py",
		"; sprites 0–1 = white/red overlay; 2+ = base layers (brightest first)",
		f"CURSOR_SPR_COUNT\t= {n}",
		f"CURSOR_OVERLAY_COUNT\t= 2",
		f"CURSOR_BASE_MASK\t= %{format(((1 << n) - 1) & ~3, '08b')}",
		f"CURSOR_OVERLAY_MASK\t= %00000011",
		f"CURSOR_SPR_W\t= {SPR_W}",
		f"cursor_spr_cols\t!byte {col_bytes}\t; {col_names}",
		"",
		"menu_cursor_spr",
	]
	lines.extend(fmt_bytes(blobs))
	lines.append("")
	OUT.parent.mkdir(parents=True, exist_ok=True)
	OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
	preview.save(PREVIEW)
	print(f"wrote {OUT.relative_to(ROOT)} layers={n} cols={col_names}")


if __name__ == "__main__":
	main()
