#!/usr/bin/env python3
"""Bake screens/logo.bin + charset.asm into tmp/menu_logo.asm for bitmap blit."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOGO_BIN = ROOT / "screens" / "logo.bin"
CHARSET = ROOT / "charset.asm"
OUT = ROOT / "tmp" / "menu_logo.asm"

LOGO_W = 26
LOGO_H = 13
LOGO_COL = 7
LOGO_ROW = 1


def parse_charset(path: Path) -> list[list[int]]:
	bytes_: list[int] = []
	for line in path.read_text(encoding="utf-8").splitlines():
		s = line.strip()
		if not s.startswith("!byte"):
			continue
		for m in re.finditer(r"\$([0-9A-Fa-f]{2})", s.split(";")[0]):
			bytes_.append(int(m.group(1), 16))
	if len(bytes_) < 848:
		raise SystemExit(f"charset.asm too short: {len(bytes_)}")
	glyphs = [bytes_[i : i + 8] for i in range(0, 848, 8)]
	return glyphs


def fmt(g: list[int]) -> str:
	return ",".join(f"${b:02x}" for b in g)


def main() -> None:
	raw = LOGO_BIN.read_bytes()
	# pair_count is in logo_defs; 20 pairs * 2 + rle
	# Read pair count from logo_defs.asm
	defs = (ROOT / "logo_defs.asm").read_text(encoding="utf-8")
	m = re.search(r"LOGO_PAIR_COUNT = (\d+)", defs)
	if not m:
		raise SystemExit("LOGO_PAIR_COUNT missing")
	n = int(m.group(1))
	pair_chars = list(raw[:n])
	pair_cols = list(raw[n : n * 2])
	rle = list(raw[n * 2 :])
	glyphs = parse_charset(CHARSET)
	uniq = []
	seen = {}
	glyph_bytes: list[list[int]] = []
	for ch in pair_chars:
		if ch not in seen:
			seen[ch] = len(uniq)
			uniq.append(ch)
			if ch >= len(glyphs):
				raise SystemExit(f"logo char {ch} past charset")
			glyph_bytes.append(glyphs[ch])
	remap = [seen[ch] for ch in pair_chars]

	lines = [
		"; Auto-generated by tools/gen_menu_logo.py from logo.bin + charset.asm",
		f"MENU_LOGO_SPR_COUNT\t= 0",
		f"MENU_LOGO_COLS\t= {LOGO_W}",
		f"MENU_LOGO_ROWS\t= {LOGO_H}",
		f"MENU_LOGO_PAD_Y\t= 0",
		f"MENU_LOGO_SPR_OFF_Y\t= 0",
		f"LOGO_W\t= {LOGO_W}",
		f"LOGO_H\t= {LOGO_H}",
		f"LOGO_COL\t= {LOGO_COL}",
		f"LOGO_ROW\t= {LOGO_ROW}",
		f"LOGO_PAIR_COUNT\t= {n}",
		f"LOGO_RLE_COUNT\t= {len(rle)}",
		f"LOGO_GLYPH_COUNT\t= {len(uniq)}",
		"",
		"menu_logo_pair_idx",
		"\t!byte " + ",".join(f"${b:02x}" for b in remap),
		"menu_logo_pair_cols",
		"\t!byte " + ",".join(f"${b:02x}" for b in pair_cols),
		"menu_logo_rle",
		"\t!byte " + ",".join(f"${b:02x}" for b in rle),
		"menu_logo_glyphs",
	]
	for i, g in enumerate(glyph_bytes):
		lines.append(f"\t!byte {fmt(g)}\t; pair glyph {i} charset {uniq[i]}")
	lines.append("")
	OUT.parent.mkdir(parents=True, exist_ok=True)
	OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
	print(f"wrote {OUT.relative_to(ROOT)} pairs={n} glyphs={len(uniq)} rle={len(rle)}")


if __name__ == "__main__":
	main()
