#!/usr/bin/env node
'use strict';
const fs = require('fs');
const path = require('path');
const { LOGO_REMAP } = require('./gencharset.js');

const src = fs.readFileSync(path.join(__dirname, '..', 'logo_raw.asm'), 'utf8');

function parseBytes(label) {
  const re = new RegExp(label + '[\\s\\S]*?(?=\\n\\w|$)');
  const block = src.match(re)[0];
  return [...block.matchAll(/\$([0-9A-Fa-f]{2})/g)].map((m) => parseInt(m[1], 16));
}

function remapChar(c) {
  if (Object.prototype.hasOwnProperty.call(LOGO_REMAP, c)) return LOGO_REMAP[c];
  throw new Error(`logo char $${c.toString(16)} has no packed-slot remap`);
}

const chars = parseBytes('logo_chars').map(remapChar);
const cols = parseBytes('logo_cols');
const W = 26;
const H = 13;
if (chars.length !== W * H) {
  throw new Error(`expected ${W * H} cells, got ${chars.length}`);
}

const pairs = [];
const pairIndex = new Map();
function pairId(c, col) {
  const key = `${c},${col}`;
  if (!pairIndex.has(key)) {
    pairIndex.set(key, pairs.length);
    pairs.push([c, col]);
  }
  return pairIndex.get(key);
}

// Packed token: index[7:3] | (run_len-1)[2:0]  — run 1..8; longer runs split
const packed = [];
for (let row = 0; row < H; row++) {
  let i = row * W;
  const end = i + W;
  while (i < end) {
    const c = chars[i];
    const col = cols[i];
    let len = 1;
    while (i + len < end && chars[i + len] === c && cols[i + len] === col) {
      len++;
    }
    const id = pairId(c, col);
    if (id > 31) {
      throw new Error(`pair index ${id} exceeds 5-bit field`);
    }
    let rem = len;
    while (rem > 0) {
      const chunk = rem > 8 ? 8 : rem;
      packed.push((id << 3) | (chunk - 1));
      rem -= chunk;
    }
    i += len;
  }
}

const pairChars = pairs.map((p) => p[0]);
const pairCols = pairs.map((p) => p[1]);
const payload = Buffer.from([...pairChars, ...pairCols, ...packed]);

const screensDir = path.join(__dirname, '..', 'screens');
fs.mkdirSync(screensDir, { recursive: true });
const binDest = path.join(screensDir, 'logo.bin');
fs.writeFileSync(binDest, payload);

// Resident constants only — payload loads into FRAMEBUFFER at runtime
const defs = [];
defs.push('; Logo layout constants — payload is screens/logo.bin → FRAMEBUFFER');
defs.push('; Generated by tools/genlogo.js');
defs.push('LOGO_W = 26');
defs.push('LOGO_H = 13');
defs.push('LOGO_COL = 7\t\t; centered in 40 columns');
defs.push('LOGO_ROW = 1');
defs.push('LOGO_PAIR_COUNT = ' + pairs.length);
defs.push('LOGO_RLE_COUNT = ' + packed.length);
defs.push('LOGO_PAIR_CHARS = FRAMEBUFFER');
defs.push('LOGO_PAIR_COLS = FRAMEBUFFER + LOGO_PAIR_COUNT');
defs.push('LOGO_RLE = FRAMEBUFFER + LOGO_PAIR_COUNT * 2');
defs.push('');

const defsDest = path.join(__dirname, '..', 'logo_defs.asm');
fs.writeFileSync(defsDest, defs.join('\n') + '\n');

console.log(
  `pairs=${pairs.length} tokens=${packed.length} raw=${chars.length} bin=${payload.length} bytes`
);
console.log('wrote', binDest);
console.log('wrote', defsDest);
