#!/usr/bin/env node
'use strict';
const fs = require('fs');
const path = require('path');

const src = fs.readFileSync(path.join(__dirname, '..', 'logo_raw.asm'), 'utf8');

function parseBytes(label) {
  const re = new RegExp(label + '[\\s\\S]*?(?=\\n\\w|$)');
  const block = src.match(re)[0];
  return [...block.matchAll(/\$([0-9A-Fa-f]{2})/g)].map((m) => parseInt(m[1], 16));
}

const chars = parseBytes('logo_chars');
const cols = parseBytes('logo_cols');
const W = 26;
const H = 13;
if (chars.length !== W * H) {
  throw new Error(`expected ${W * H} cells, got ${chars.length}`);
}

const pairs = [];
const pairIndex = new Map();
function pairId(c, col) {
  const key = `${c},${col}`;
  if (!pairIndex.has(key)) {
    pairIndex.set(key, pairs.length);
    pairs.push([c, col]);
  }
  return pairIndex.get(key);
}

const runs = [];
const ids = [];
for (let row = 0; row < H; row++) {
  let i = row * W;
  const end = i + W;
  while (i < end) {
    const c = chars[i];
    const col = cols[i];
    let len = 1;
    while (i + len < end && chars[i + len] === c && cols[i + len] === col) {
      len++;
    }
    runs.push(len);
    ids.push(pairId(c, col));
    i += len;
  }
}

const hex = (n) => '$' + n.toString(16).toUpperCase().padStart(2, '0');
function fmt(arr) {
  let s = '';
  for (let i = 0; i < arr.length; i++) {
    if (i % 16 === 0) {
      s += (s ? '\n' : '') + '\t!BYTE\t';
    } else {
      s += ', ';
    }
    s += hex(arr[i]);
  }
  return s;
}

const out = [];
out.push('; PETSCII logo 26x13 — RLE + (char,color) lookup');
out.push('; Generated by tools/genlogo.js from logo_raw.asm');
out.push('; Glyphs are standard CHARROM PETSCII ($A0,$DF,$E6,…) — init_charset copies ROM then patches dither.'); 
out.push('LOGO_W = 26');
out.push('LOGO_H = 13');
out.push('LOGO_COL = 7\t\t; centered in 40 columns');
out.push('LOGO_ROW = 1');
out.push('');
out.push('logo_pair_chars');
out.push(fmt(pairs.map((p) => p[0])));
out.push('');
out.push('logo_pair_cols');
out.push(fmt(pairs.map((p) => p[1])));
out.push('');
out.push('logo_rle_runs');
out.push(fmt(runs));
out.push('');
out.push('logo_rle_ids');
out.push(fmt(ids));
out.push('');
out.push('LOGO_PAIR_COUNT = ' + pairs.length);
out.push('LOGO_RLE_COUNT = ' + runs.length);

const dest = path.join(__dirname, '..', 'logo.asm');
fs.writeFileSync(dest, out.join('\n') + '\n');
console.log(`pairs=${pairs.length} runs=${runs.length} raw=${chars.length} out=${pairs.length * 2 + runs.length * 2} bytes`);
console.log('wrote', dest);
