/**
 * Build dpsounds.asm from Doom PC speaker DP*.lmp + speaker.txt freqs.
 * Pitch bytes 0..95 → SID frequency (NTSC φ2); voice uses pulse (square-ish).
 */
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pcs = join(root, 'pcsounds');

// Same order as VicDoom soundTable / ESound
const EFFECTS = [
  'dpclaw', 'dpdmpain', 'dpdoropn', 'dpdorcls', 'dpitemup', 'dpoof',
  'dpbgact', 'dppistol', 'dpplpain', 'dppopain', 'dpsgcock', 'dpsgtdth',
  'dpshotgn', 'dpstnmov', 'dpsawidl', 'dpsawful', 'dpsawhit', 'dppunch',
  'dpbarexp',
];

const PHI2_NTSC = 1022727;
const SID_CLOCK_DIV = 16777216;

function parseSpeakerFreqs(text) {
  const hz = new Array(96).fill(0);
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(/^(\d+)\s+(\d+|-)\s+([\d.]+|-)/);
    if (!m) continue;
    const v = +m[1];
    if (v >= 1 && v <= 95 && m[3] !== '-') hz[v] = +m[3];
  }
  return hz;
}

function sidFn(hz) {
  if (hz <= 0) return 0;
  return Math.max(0, Math.min(65535, Math.round((hz * SID_CLOCK_DIV) / PHI2_NTSC)));
}

function readLmp(name) {
  const buf = readFileSync(join(pcs, `${name}.lmp`));
  const len = buf[2] | (buf[3] << 8);
  const data = [...buf.subarray(4, 4 + len)];
  if (data.length !== len) {
    throw new Error(`${name}: truncated (header ${len}, got ${data.length})`);
  }
  for (const b of data) {
    if (b > 95) throw new Error(`${name}: pitch ${b} out of range`);
  }
  return data;
}

function emitBytes(arr, perLine = 16) {
  const lines = [];
  for (let i = 0; i < arr.length; i += perLine) {
    const chunk = arr.slice(i, i + perLine);
    lines.push('\t!byte ' + chunk.join(', '));
  }
  return lines.join('\n');
}

const hz = parseSpeakerFreqs(readFileSync(join(pcs, 'speaker.txt'), 'utf8'));
const fn = hz.map(sidFn);

let total = 0;
let uniqueTotal = 0;
const outBlocks = [];
const aliases = [];
const payloadLabels = new Map();
for (const name of EFFECTS) {
  const data = readLmp(name);
  total += 1 + data.length;
  const key = data.join(',');
  const canonical = payloadLabels.get(key);
  if (canonical) {
    aliases.push(`${name} = ${canonical}`);
    continue;
  }
  payloadLabels.set(key, name);
  uniqueTotal += 1 + data.length;
  const body = [data.length, ...data];
  outBlocks.push(`${name}\n${emitBytes(body)}`);
}

const lo = fn.map((v) => v & 0xff);
const hi = fn.map((v) => (v >> 8) & 0xff);

const asm = `; Autogenerated by tools/gensounds.js — Doom PC speaker DP* lumps + freq table.
; Each effect: first byte = sample count; following = pitch 0..95 (0 = silence).
; pcsfreq_* lives in pcsfreq.asm (flush under py_tab; keeps kernal blob ≤ scrap size).

!zone dpsounds

${outBlocks.join('\n')}

; Byte-identical effects share one payload without changing table lookup cost.
${aliases.join('\n')}

; unique sound payload ${uniqueTotal} bytes (${total - uniqueTotal} deduplicated)
sound_table
${EFFECTS.map((n) => `\t!word ${n}`).join('\n')}
`;

const pcsfreqAsm = `; Autogenerated by tools/gensounds.js — pitch → SID Fn (NTSC φ2).
; Placed flush under py_tab by squaredoom.asm.

!zone pcsfreq

; Pitch 0..95 → SID Fn (0 = silence). From pcsounds/speaker.txt × NTSC φ2.
pcsfreq_lo
${emitBytes(lo)}
pcsfreq_hi
${emitBytes(hi)}
`;

writeFileSync(join(root, 'dpsounds.asm'), asm);
writeFileSync(join(root, 'pcsfreq.asm'), pcsfreqAsm);
console.log(`wrote dpsounds.asm (${EFFECTS.length} effects, ${uniqueTotal} unique sample bytes, ${total - uniqueTotal} deduplicated) + pcsfreq.asm (96 entries)`);
